In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
from googleapiclient.discovery import build
import pandas as pd
import json
from collections import OrderedDict

In [4]:
df = pd.read_excel('/content/drive/MyDrive/KOBIS_역대_박스오피스_내역(공식통계_기준)_2022-06-26.xlsx', 
                   usecols = ['영화명', '개봉일', '매출액', 'Unnamed: 5'], header = 4)
df.head()

           영화명        개봉일           매출액  Unnamed: 5
0          명량  2014-07-30  1.357484e+11  17613682.0
1        극한직업  2019-01-23  1.396480e+11  16264944.0
2   신과함께-죄와 벌  2017-12-20  1.156987e+11  14410754.0
3        국제시장  2014-12-17  1.109135e+11  14257115.0
4  어벤져스: 엔드게임  2019-04-24  1.221827e+11  13934592.0

In [5]:
df.rename(columns={'Unnamed: 5':'관객수(S: 서울 기준)'}, inplace=True)
df.head()

           영화명        개봉일           매출액  관객수(S: 서울 기준)
0          명량  2014-07-30  1.357484e+11     17613682.0
1        극한직업  2019-01-23  1.396480e+11     16264944.0
2   신과함께-죄와 벌  2017-12-20  1.156987e+11     14410754.0
3        국제시장  2014-12-17  1.109135e+11     14257115.0
4  어벤져스: 엔드게임  2019-04-24  1.221827e+11     13934592.0

In [6]:
df = df.fillna(df.mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   영화명            500 non-null    object
 1   개봉일            500 non-null    datetime64[ns]
 2   매출액            500 non-null    float64
 3   관객수(S: 서울 기준)  500 non-null    float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 15.8+ KB

In [7]:
df = df.head(50)
df

                  영화명        개봉일           매출액  관객수(S: 서울 기준)
0                 명량  2014-07-30  1.357484e+11     17613682.0
1               극한직업  2019-01-23  1.396480e+11     16264944.0
2          신과함께-죄와 벌  2017-12-20  1.156987e+11     14410754.0
3               국제시장  2014-12-17  1.109135e+11     14257115.0
4         어벤져스: 엔드게임  2019-04-24  1.221827e+11     13934592.0
5             겨울왕국 2  2019-11-21  1.148104e+11     13747792.0
6                아바타  2009-12-17  1.284471e+11     13624328.0
7                베테랑  2015-08-05  1.051682e+11     13414009.0
8                 괴물  2006-07-27  0.000000e+00     13019740.0
9                도둑들  2012-07-25  9.366557e+10     12983330.0
10           7번방의 선물  2013-01-23  9.143191e+10     12811206.0
11                암살  2015-07-22  9.846313e+10     12705700.0
12               알라딘  2019-05-23  1.069836e+11     12555894.0
13       광해, 왕이 된 남자  2012-09-13  8.890021e+10     12319542.0
14             왕의 남자  2005-12-29  0.000000e+00     12302831.0
15         신과함께-인과 연  2018-08-01  1.026661e+11     12274996.0
16             택시운전사  2017-08-02  9.585574e+10     12186684.0
17          태극기 휘날리며  2004-02-05  0.000000e+00     11746135.0
18               부산행  2016-07-20  9.317828e+10     11565479.0
19               해운대  2009-07-22  8.193464e+10     11453338.0
20               변호인  2013-12-18  8.287176e+10     11374610.0
21      어벤져스: 인피니티 워  2018-04-25  9.991901e+10     11211880.0
22               실미도  2003-12-24  0.000000e+00     11081000.0
23  어벤져스: 에이지 오브 울트론  2015-04-23  8.858259e+10     10494499.0
24               기생충  2019-05-30  8.745983e+10     10313086.0
25              겨울왕국  2014-01-16  8.246150e+10     10296101.0
26             인터스텔라  2014-11-06  8.229109e+10     10275484.0
27          보헤미안 랩소디  2018-10-31  8.628098e+10      9948386.0
28              검사외전  2016-02-03  7.731945e+10      9707158.0
29               엑시트  2019-07-31  7.923221e+10      9426051.0
30              설국열차  2013-08-01  6.701008e+10      9349991.0
31                관상  2013-09-11  6.600545e+10      9134586.0
32            아이언맨 3  2013-04-25  7.080619e+10      9001309.0
33     캡틴 아메리카: 시빌 워  2016-04-27  7.267211e+10      8677249.0
34      해적: 바다로 간 산적  2014-08-06  6.637068e+10      8666046.0
35            수상한 그녀  2014-01-22  6.269664e+10      8656397.0
36              국가대표  2009-07-29  6.089663e+10      8487894.0
37                디워  2007-08-01  0.000000e+00      8426973.0
38               백두산  2019-12-19  6.982537e+10      8252669.0
39             과속스캔들  2008-12-03  5.394010e+10      8245523.0
40     스파이더맨: 파 프롬 홈  2019-07-02  6.900927e+10      8021064.0
41          웰컴 투 동막골  2005-08-04  0.000000e+00      8008622.0
42                공조  2017-01-18  6.378173e+10      7817446.0
43           트랜스포머 3  2011-06-29  7.484135e+10      7784807.0
44              히말라야  2015-12-16  6.017358e+10      7759473.0
45    미션임파서블:고스트프로토콜  2011-12-15  5.779585e+10      7575899.0
46     스파이더맨: 노 웨이 홈  2021-12-15  7.519366e+10      7551946.0
47     트랜스포머: 패자의 역습  2009-06-24  5.147853e+10      7505700.0
48                밀정  2016-09-07  6.126978e+10      7500420.0
49            최종병기 활  2011-08-10  5.582786e+10      7470633.0

In [8]:
df['개봉일'] = df['개봉일'].astype('str')

In [9]:
movie_name = df['영화명'].to_list()
opening_date = df['개봉일'].to_list()
sales_amount = df['매출액'].to_list()
number_of_spectoators = df['관객수(S: 서울 기준)'].to_list()

In [10]:
box_office_data = OrderedDict()

In [11]:
box_office_data['movie_name'] = movie_name
box_office_data['opening_date'] = opening_date
box_office_data['sales_amount'] = sales_amount
box_office_data['number_of_spectoators'] = number_of_spectoators

In [12]:
print(json.dumps(box_office_data, ensure_ascii=False, indent='\t'))

{
	"movie_name": [
		"명량 ",
		"극한직업 ",
		"신과함께-죄와 벌 ",
		"국제시장 ",
		"어벤져스: 엔드게임 ",
		"겨울왕국 2 ",
		"아바타 ",
		"베테랑 ",
		"괴물 ",
		"도둑들 ",
		"7번방의 선물 ",
		"암살 ",
		"알라딘 ",
		"광해, 왕이 된 남자 ",
		"왕의 남자 ",
		"신과함께-인과 연 ",
		"택시운전사 ",
		"태극기 휘날리며 ",
		"부산행 ",
		"해운대 ",
		"변호인 ",
		"어벤져스: 인피니티 워 ",
		"실미도 ",
		"어벤져스: 에이지 오브 울트론 ",
		"기생충 ",
		"겨울왕국 ",
		"인터스텔라 ",
		"보헤미안 랩소디 ",
		"검사외전 ",
		"엑시트 ",
		"설국열차 ",
		"관상 ",
		"아이언맨 3 ",
		"캡틴 아메리카: 시빌 워 ",
		"해적: 바다로 간 산적 ",
		"수상한 그녀 ",
		"국가대표 ",
		"디워 ",
		"백두산 ",
		"과속스캔들 ",
		"스파이더맨: 파 프롬 홈 ",
		"웰컴 투 동막골 ",
		"공조 ",
		"트랜스포머 3 ",
		"히말라야 ",
		"미션임파서블:고스트프로토콜 ",
		"스파이더맨: 노 웨이 홈 ",
		"트랜스포머: 패자의 역습 ",
		"밀정 ",
		"최종병기 활 "
	],
	"opening_date": [
		"2014-07-30",
		"2019-01-23",
		"2017-12-20",
		"2014-12-17",
		"2019-04-24",
		"2019-11-21",
		"2009-12-17",
		"2015-08-05",
		"2006-07-27",
		"2012-07-25",
		"2013-01-23",
		"2015-07-22",
		"2019-05-23",
		"2012-09-13",
		"2005-12-29",
		"2018-08-01",
		"2017-08-02",
		"2004-02-05",
		"2016-07-20",
		"2009-07-22",
		"2013-12-18",
		"2018-04-25",
		"2003-12-24",
		"2015-04-23",
		"2019-05-30",
		"2014-01-16",
		"2014-11-06",
		"2018-10-31",
		"2016-02-03",
		"2019-07-31",
		"2013-08-01",
		"2013-09-11",
		"2013-04-25",
		"2016-04-27",
		"2014-08-06",
		"2014-01-22",
		"2009-07-29",
		"2007-08-01",
		"2019-12-19",
		"2008-12-03",
		"2019-07-02",
		"2005-08-04",
		"2017-01-18",
		"2011-06-29",
		"2015-12-16",
		"2011-12-15",
		"2021-12-15",
		"2009-06-24",
		"2016-09-07",
		"2011-08-10"
	],
	"sales_amount": [
		135748398910.0,
		139647979516.0,
		115698654137.0,
		110913469630.0,
		122182694160.0,
		114810421450.0,
		128447097523.0,
		105168155250.0,
		0.0,
		93665568500.0,
		91431914670.0,
		98463132781.0,
		106983620359.0,
		88900208769.0,
		0.0,
		102666146909.0,
		95855737149.0,
		0.0,
		93178283048.0,
		81934638201.0,
		82871759300.0,
		99919006769.0,
		0.0,
		88582586366.0,
		87459829095.0,
		82461504400.0,
		82291089200.0,
		86280975785.0,
		77319445264.0,
		79232212162.0,
		67010077500.0,
		66005451500.0,
		70806191000.0,
		72672111827.0,
		66370682706.0,
		62696639249.0,
		60896633308.0,
		0.0,
		69825366300.0,
		53940101534.0,
		69009271100.0,
		0.0,
		63781731326.0,
		74841350500.0,
		60173583015.0,
		57795846000.0,
		75193655210.0,
		51478531663.0,
		61269783831.0,
		55827861500.0
	],
	"number_of_spectoators": [
		17613682.0,
		16264944.0,
		14410754.0,
		14257115.0,
		13934592.0,
		13747792.0,
		13624328.0,
		13414009.0,
		13019740.0,
		12983330.0,
		12811206.0,
		12705700.0,
		12555894.0,
		12319542.0,
		12302831.0,
		12274996.0,
		12186684.0,
		11746135.0,
		11565479.0,
		11453338.0,
		11374610.0,
		11211880.0,
		11081000.0,
		10494499.0,
		10313086.0,
		10296101.0,
		10275484.0,
		9948386.0,
		9707158.0,
		9426051.0,
		9349991.0,
		9134586.0,
		9001309.0,
		8677249.0,
		8666046.0,
		8656397.0,
		8487894.0,
		8426973.0,
		8252669.0,
		8245523.0,
		8021064.0,
		8008622.0,
		7817446.0,
		7784807.0,
		7759473.0,
		7575899.0,
		7551946.0,
		7505700.0,
		7500420.0,
		7470633.0
	]
}

In [13]:
with open('box_office_etc.json', 'w', encoding='utf-8') as make_file:
  json.dump(box_office_data, make_file, ensure_ascii=False, indent='\t')